version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.0

jobs:
  setup:
    docker:
      - image: gueraf/cuda_bazel:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: "Generate config"
          command: .circleci/generate_circleci_config.sh
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml

workflows:
  setup-workflow:
    jobs:
      - setup
